import { CursoDetalheEncadeado } from "./types";

export const mockCursoCV: CursoDetalheEncadeado = {
  id: 130,
  nome: "Marketing Digital Avançado",
  entidade: "NOSiAkademia",
  coordenador: "Prof. Ana Silva",
  dataInicio: "2025-03-15",
  dataFim: "2025-06-15",
  horasCompletas: 75,
  cargaHoraria: 120,
  proximaAula: "2025-04-25 - 14:00",
  progresso: 62,
  status: "em_curso",
  modulos: [
    {
      id: "md-01",
      codigo: "MD-01",
      nome: "Fundamentos do Marketing Digital",
      horas: 20,
      completo: true,
      progresso: 100,
      totalUFs: 2,
      totalSessoes: 4,
      ufs: [
        {
          id: "uf-101",
          codigo: "UF-MKT-01",
          nome: "Introdução ao Ecossistema Digital",
          cargaHoraria: 10,
          secoes: 2,
          sessoes: [
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
            {
              id: "s-101",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Sala 2",
              tipoConteudo: "Panorama de canais e métricas",
              formaAvaliacao: "Quiz",
              duracaoMin: 120,
              data: "2025-03-18",
              hora: "14:00",
            },
            {
              id: "s-102",
              numero: 2,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-1", nome: "João Pina (IEFP Praia)" },
              local: "IEFP Praia — Lab A",
              tipoConteudo: "Definição de objetivos SMART",
              formaAvaliacao: "Trabalho",
              duracaoMin: 120,
              data: "2025-03-20",
              hora: "14:00",
            },
          ],
        },
        {
          id: "uf-102",
          codigo: "UF-MKT-02",
          nome: "Comportamento do Consumidor Online",
          cargaHoraria: 10,
          secoes: 2,
          sessoes: [
            {
              id: "s-103",
              numero: 1,
              status: "pendente",
              tipologia: "teorica",
              formador: { id: "f-2", nome: "Maria Silva (Uni-CV)" },
              local: "Uni-CV — Auditório",
              tipoConteudo: "Psicologia do consumidor digital",
              duracaoMin: 90,
              data: "2025-04-10",
              hora: "10:00",
            },
            {
              id: "s-104",
              numero: 2,
              status: "pendente",
              tipologia: "pratica",
              formador: { id: "f-2", nome: "Maria Silva (Uni-CV)" },
              local: "Uni-CV — Sala TIC",
              tipoConteudo: "Estudos de caso CV",
              duracaoMin: 90,
              data: "2025-04-12",
              hora: "14:00",
            },
          ],
        },
      ],
    },
    {
      id: "md-02",
      codigo: "MD-02",
      nome: "SEO e SEM",
      horas: 25,
      completo: false,
      progresso: 60,
      totalUFs: 3,
      totalSessoes: 6,
      ufs: [
        {
          id: "uf-201",
          codigo: "UF-SEO-01",
          nome: "SEO On-page",
          cargaHoraria: 12,
          secoes: 3,
          sessoes: [
            {
              id: "s-201",
              numero: 1,
              status: "concluida",
              tipologia: "laboratorio",
              formador: { id: "f-3", nome: "Carlos Mendes (IEFP Mindelo)" },
              local: "IEFP Mindelo — Sala TIC",
              tipoConteudo: "Palavras-chave e estrutura HTML",
              duracaoMin: 120,
              data: "2025-04-05",
              hora: "09:30",
            },
            {
              id: "s-202",
              numero: 2,
              status: "pendente",
              tipologia: "teorica",
              formador: { id: "f-3", nome: "Carlos Mendes (IEFP Mindelo)" },
              local: "IEFP Mindelo — Sala TIC",
              tipoConteudo: "SEO técnico e Core Web Vitals",
              duracaoMin: 120,
              data: "2025-04-12",
              hora: "09:30",
            },
          ],
        },
        {
          id: "uf-202",
          codigo: "UF-SEM-01",
          nome: "Campanhas SEM",
          cargaHoraria: 8,
          secoes: 2,
          sessoes: [
            {
              id: "s-203",
              numero: 1,
              status: "pendente",
              tipologia: "pratica",
              formador: { id: "f-4", nome: "Sara Fortes (NOSiAkademia)" },
              local: "NOSi Plateau — Sala 3",
              tipoConteudo: "Configuração Google Ads",
              duracaoMin: 100,
              data: "2025-04-20",
              hora: "14:00",
            },
          ],
        },
        {
          id: "uf-203",
          codigo: "UF-SEM-02",
          nome: "Analytics para SEM",
          cargaHoraria: 5,
          secoes: 1,
          sessoes: [
            {
              id: "s-204",
              numero: 1,
              status: "pendente",
              tipologia: "teorica",
              formador: { id: "f-5", nome: "Ana Rocha (Uni-CV)" },
              local: "Uni-CV — Campus Palmarejo",
              tipoConteudo: "Medição de KPIs e conversões",
              duracaoMin: 90,
              data: "2025-04-28",
              hora: "16:00",
            },
          ],
        },
      ],
    },
    {
      id: "md-03",
      codigo: "MD-03",
      nome: "Redes Sociais",
      horas: 30,
      completo: true,
      progresso: 100,
      totalUFs: 2,
      totalSessoes: 3,
      ufs: [
        {
          id: "uf-301",
          codigo: "UF-SOC-01",
          nome: "Conteúdo e Planeamento",
          cargaHoraria: 12,
          secoes: 2,
          sessoes: [
            {
              id: "s-301",
              numero: 1,
              status: "concluida",
              tipologia: "pratica",
              formador: { id: "f-6", nome: "Paula Lima (NOSi)" },
              local: "NOSi Plateau — Sala 4",
              tipoConteudo: "Calendário editorial Cabo Verde",
              duracaoMin: 120,
              data: "2025-03-28",
              hora: "10:00",
            },
          ],
        },
        {
          id: "uf-302",
          codigo: "UF-SOC-02",
          nome: "Gestão de Campanhas",
          cargaHoraria: 18,
          secoes: 3,
          sessoes: [
            {
              id: "s-302",
              numero: 1,
              status: "concluida",
              tipologia: "laboratorio",
              formador: { id: "f-7", nome: "Rui Faria (IEFP Praia)" },
              local: "IEFP Praia — Lab B",
              tipoConteudo: "Gestão de Ads em Facebook",
              duracaoMin: 100,
              data: "2025-04-01",
              hora: "09:00",
            },
            {
              id: "s-303",
              numero: 2,
              status: "pendente",
              tipologia: "pratica",
              formador: { id: "f-7", nome: "Rui Faria (IEFP Praia)" },
              local: "IEFP Praia — Lab B",
              tipoConteudo: "Análise de métricas Instagram",
              duracaoMin: 100,
              data: "2025-04-15",
              hora: "09:00",
            },
          ],
        },
      ],
    },
    {
      id: "md-04",
      codigo: "MD-04",
      nome: "Email Marketing",
      horas: 15,
      completo: false,
      progresso: 40,
      totalUFs: 1,
      totalSessoes: 2,
      ufs: [
        {
          id: "uf-401",
          codigo: "UF-EMAIL-01",
          nome: "Campanhas de Email",
          cargaHoraria: 15,
          secoes: 2,
          sessoes: [
            {
              id: "s-401",
              numero: 1,
              status: "concluida",
              tipologia: "teorica",
              formador: { id: "f-8", nome: "Vera Gomes (Uni-CV)" },
              local: "Uni-CV — Palmarejo",
              tipoConteudo: "Boas práticas de email marketing",
              duracaoMin: 80,
              data: "2025-03-22",
              hora: "10:00",
            },
            {
              id: "s-402",
              numero: 2,
              status: "pendente",
              tipologia: "pratica",
              formador: { id: "f-8", nome: "Vera Gomes (Uni-CV)" },
              local: "Uni-CV — Palmarejo",
              tipoConteudo: "Ferramentas e automação",
              duracaoMin: 90,
              data: "2025-04-22",
              hora: "10:00",
            },
          ],
        },
      ],
    },
  ],
};
